rails_link: "http://www.railstutorial.org/book"
ror: "http://rubyonrails.org/"
screencast_series: "http://screencasts.railstutorial.org/"
ror_tutorial: "http://www.railstutorial.org/"
rails_help: "http://www.railstutorial.org/help"
rails_tutorial: "http://www.railstutorial.org/book"
michael_hartl: "http://www.michaelhartl.com/"
news: "http://news.railstutorial.org/"
rails_contact: "http://www.railstutorial.org/contact"
max_num: 50
max_email: 255
min_num: 6
user_size: 80
checbox_checked: 1
password: "password"
num_one: "1"
